{% set name = "pytest-doctest-ufunc" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest-doctest-ufunc-{{ version }}.tar.gz
  sha256: 958adb5c2c11d6462e4331c43fe77fd991fdfa8767fc417353b8f0c8829e6112

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy
    - pytest >=3.5.0
    - python >={{ python_min }}

test:
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    # check requirements
    - python -m pip check
    # check that pytest recognises the plugin
    - python -m pytest --traceconfig | grep {{ name }}-{{ version }}

about:
  home: https://github.com/lpsinger/pytest-doctest-ufunc
  summary: A plugin to run doctests in docstrings of Numpy ufuncs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - duncanmmacleod
    - lpsinger
